# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('create_datatime', models.DateTimeField(auto_now_add=True)),
                ('creae_data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='creae_data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='create_datatime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='index',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
