# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171205_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jun',
            old_name='creae_data',
            new_name='create_data',
        ),
    ]
